version: 0.2

phases:
  install:
    commands:
      - cd express-api
      - npm i
  #pre_build:
    #commands:
      # - command
  build:
    commands:
      - npm test
      - rm -rf express-api/test
      - sam package --s3-bucket $BUILD_S3_BUCKET --s3-prefix express-api --output-template-file template_packaged.yaml
  post_build:
    commands:
      - sam deploy --stack-name $DEPLOY_STACK_NAME --s3-bucket $BUILD_S3_BUCKET --capabilities CAPABILITY_IAM --template template_packaged.yaml
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - '**/*'
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  base-directory: express-api
#cache:
  #paths:
    # - pathscodebuild-build-docker-example-service-role
