version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "ExpressAPIFunction"
        Alias: "latest"
        CurrentVersion: "1"
        TargetVersion: "2"
# Hooks:
#   - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
#   - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
