AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API service using SAM Lambda

Resources:
  ExpressAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: express-api.handler
      Runtime: nodejs12.x
      Events:
        RootResource:
          Type: Api
          Properties:
            Path: /
            Method: get
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get
Outputs:
  APIURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
